"""initial: users, places, place_signals

Revision ID: 9e0415db744a
Revises: 
Create Date: 2026-05-21 13:00:06.448303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.migration_indexes import create_uq_places_external, drop_uq_places_external


# revision identifiers, used by Alembic.
revision: str = '9e0415db744a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('external_provider', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_places_business', 'places', ['business_id'], unique=False)
    op.create_index('idx_places_district_category', 'places', ['district', 'category'], unique=False)
    create_uq_places_external()
    op.create_table('users',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_region', 'users', ['region'], unique=False)
    op.create_table('place_signals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('place_id', sa.String(length=32), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source_ref', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_place_time', 'place_signals', ['place_id', 'occurred_at'], unique=False)
    op.create_index('idx_signals_source', 'place_signals', ['source_ref'], unique=False)
    op.create_index('idx_signals_type', 'place_signals', ['signal_type', 'is_void'], unique=False)
    op.create_index('idx_signals_user', 'place_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signals_user', table_name='place_signals')
    op.drop_index('idx_signals_type', table_name='place_signals')
    op.drop_index('idx_signals_source', table_name='place_signals')
    op.drop_index('idx_signals_place_time', table_name='place_signals')
    op.drop_table('place_signals')
    op.drop_index('idx_users_region', table_name='users')
    op.drop_table('users')
    drop_uq_places_external()
    op.drop_index('idx_places_district_category', table_name='places')
    op.drop_index('idx_places_business', table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
