"""add meetings and meeting_events

Revision ID: d5eb02d614d6
Revises: 9e0415db744a
Create Date: 2026-05-21 13:44:19.539915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5eb02d614d6'
down_revision: Union[str, None] = '9e0415db744a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('host_user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meetings_district_category', 'meetings', ['district', 'category'], unique=False)
    op.create_index('idx_meetings_host', 'meetings', ['host_user_id'], unique=False)
    op.create_table('meeting_events',
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('place_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attendee_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating_dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_meeting', 'meeting_events', ['meeting_id'], unique=False)
    op.create_index('idx_events_place', 'meeting_events', ['place_id'], unique=False)
    op.create_index('idx_events_scheduled', 'meeting_events', ['scheduled_at'], unique=False)
    op.create_index('idx_events_status', 'meeting_events', ['status', 'scheduled_at'], unique=False)
    op.create_table('meeting_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_members')
    )
    op.create_index('idx_meeting_members_user', 'meeting_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_meeting_members_user', table_name='meeting_members')
    op.drop_table('meeting_members')
    op.drop_index('idx_events_status', table_name='meeting_events')
    op.drop_index('idx_events_scheduled', table_name='meeting_events')
    op.drop_index('idx_events_place', table_name='meeting_events')
    op.drop_index('idx_events_meeting', table_name='meeting_events')
    op.drop_table('meeting_events')
    op.drop_index('idx_meetings_host', table_name='meetings')
    op.drop_index('idx_meetings_district_category', table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
